changelog:
  exclude:
    labels:
      - 'rn: test(anta)'
      - 'rn: ci(anta)'
      - 'rn: test(anta.tests)'
      - 'rn: ci(anta.tests)'
      - 'rn: test(anta.cli)'
      - 'rn: ci(anta.cli)'
      - 'rn: test'
      - 'rn: ci'
  categories:
    - title: Breaking Changes
      labels:
        - 'rn: feat(anta)!'
        - 'rn: feat(anta.tests)!'
        - 'rn: feat(anta.cli)!'
        - 'rn: fix(anta)!'
        - 'rn: fix(anta.tests)!'
        - 'rn: fix(anta.cli)!'
        - 'rn: cut(anta)!'
        - 'rn: cut(anta.tests)!'
        - 'rn: cut(anta.cli)!'
        - 'rn: revert(anta)!'
        - 'rn: revert(anta.tests)!'
        - 'rn: revert(anta.cli)!'
        - 'rn: refactor(anta)!'
        - 'rn: refactor(anta.tests)!'
        - 'rn: refactor(anta.cli)!'
        - 'rn: bump(anta)!'
        - 'rn: bump(anta.tests)!'
        - 'rn: bump(anta.cli)!'
        - 'rn: feat!'
        - 'rn: fix!'
        - 'rn: cut!'
        - 'rn: revert!'
        - 'rn: refactor!'
        - 'rn: bump!'
    - title: New features and enhancements
      labels:
        - 'rn: Feat(anta)'
        - 'rn: Feat(anta.tests)'
        - 'rn: Feat(anta.cli)'
        - 'rn: Feat'
    - title: Fixed issues
      labels:
        - 'rn: Fix(anta)'
        - 'rn: Fix(anta.tests)'
        - 'rn: Fix(anta.cli)'
        - 'rn: Fix'
    - title: Documentation
      labels:
        - 'rn: Doc(anta)'
        - 'rn: Doc(anta.tests)'
        - 'rn: Doc(anta.cli)'
        - 'rn: Doc'
    - title: Other Changes
      labels:
        - '*'
