# Secret-scanner workflow from Arista Networks.
on:
  pull_request:
    types: [synchronize]
  push:
    branches:
      - main
name: Secret Scanner (go/secret-scanner)
jobs:
  scan_secret:
    name: Scan incoming changes
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: target
      - name: Run scanner
        shell: bash
        run: |
          docker run --rm -v ./target:/tmp -w /tmp --name sss-scanner \
            ghcr.io/aristanetworks/secret-scanner-service:main \
            scanner 'commit' /tmp github \
            ${{  github.repository }} \
            --markdown-file job_summary.md \
            ${{ github.event_name == 'pull_request' && format('--since-commit {0}', github.event.pull_request.base.sha) || ''}}
      - name: Write result to summary
        shell: bash
        if: ${{ always() }}
        run: cat ./target/job_summary.md >> $GITHUB_STEP_SUMMARY
